# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b441b90d010b036ee87bd0d96c175e372915cc31d852fa1cdb09b5edcb930a19ed6365f9ffb822fa58bcbbb76d8fa8f95abf02a42915fae8e88b918f8b30d59

test:
  secret_key_base: 7d86de01554252747f01ef215abaf2fb5f898069bee8836b8d169ba4bd0a4b51ef30604db98c87eba8641b425250c86d4bfc29ff9b4ee37811459c8c6d9a42ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
